### ISSUE TITLE
[FEAT] 특정 builtins 명령어 구현

### ISSUE THREAD

**Issue by kmularise** [YUIWOO/mini_shell_project#4]
> ### ISSUE
> * Type: `feature`
> * Detail: fix actions from client redux
>
> ### TODO
> 1. [ ] echo with option -n
> 2. [ ] cd with only a relative or absolute path
> 3. [ ] pwd with no options
> 4. [ ] export with no options
> 5. [ ] unset with no options
> 6. [ ] env with no options or arguments
> 7. [ ] exit with no options

**Comment by choyoungwoo9** [comment]
Good
